import { NextRequest, NextResponse } from 'next/server';
import { put } from '@vercel/blob';

export async function POST(request: NextRequest) {
  try {
    const { fighterA, fighterB } = await request.json();
    console.log('[Image Generation] Request received for:', fighterA, 'vs', fighterB);

    if (!fighterA || !fighterB) {
      console.error('[Image Generation] Missing fighter names');
      return NextResponse.json(
        { error: 'Both fighter names are required' },
        { status: 400 }
      );
    }

    // Create prompt for image generation - UFC aerial octagon view
    const prompt = `Aerial top-down view of UFC octagon during live event: Two MMA athletes ${fighterA} and ${fighterB} positioned in the center of the octagon mat with referee between them. Epic bird's eye perspective showing the complete octagon cage from above, white canvas mat visible, cage fence surrounding the fighting area. Massive crowd of spectators visible around the entire octagon perimeter, arena atmosphere with dramatic overhead lighting. Professional sports photography from elevated angle, photorealistic detail, dynamic composition showing scale of the event. Athletes in athletic shorts with MMA gloves, octagon logos on mat. NO TEXT, NO VISIBLE LABELS on the main image content.`;

    // Generate filename
    const timestamp = Date.now();
    const fileName = `${fighterA.replace(/\s+/g, '-')}-vs-${fighterB.replace(/\s+/g, '-')}-${timestamp}.png`;

    // Check if OPENAI_API_KEY is available
    const apiKey = process.env.OPENAI_API_KEY;
    
    if (!apiKey) {
      console.warn('[Image Generation] OPENAI_API_KEY not found, using placeholder image');
      return NextResponse.json({
        success: true,
        imageUrl: '/placeholder-fighter-image.png',
        prompt,
        message: 'Using placeholder - OPENAI_API_KEY not configured',
      });
    }

    console.log('[Image Generation] Calling OpenAI DALL-E 3 API...');

    // Generate image using OpenAI DALL-E API
    const openaiResponse = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'dall-e-3',
        prompt: prompt,
        n: 1,
        size: '1792x1024',
        quality: 'standard',
        response_format: 'url',
      }),
    });

    if (!openaiResponse.ok) {
      const errorData = await openaiResponse.json();
      console.error('OpenAI API error:', errorData);
      throw new Error(`OpenAI API error: ${errorData.error?.message || 'Unknown error'}`);
    }

    const imageData = await openaiResponse.json();
    const openaiImageURL = imageData.data[0]?.url;

    if (!openaiImageURL) {
      throw new Error('No image URL returned from OpenAI');
    }

    console.log('[Image Generation] Image generated by OpenAI:', openaiImageURL);

    // Check if we're in production (Vercel) or development
    const isProduction = process.env.VERCEL === '1';
    const blobToken = process.env.BLOB_READ_WRITE_TOKEN;

    let finalImageUrl = openaiImageURL;

    if (isProduction && blobToken) {
      // Production: Upload to Vercel Blob Storage
      console.log('[Image Generation] Uploading to Vercel Blob Storage...');
      
      const imageResponse = await fetch(openaiImageURL);
      const blob = await imageResponse.blob();
      
      const { url } = await put(fileName, blob, {
        access: 'public',
        token: blobToken,
      });
      
      finalImageUrl = url;
      console.log('[Image Generation] Uploaded to Vercel Blob:', finalImageUrl);
    } else {
      // Development or no blob storage: Use OpenAI URL directly
      // Note: OpenAI URLs expire after 1 hour
      console.log('[Image Generation] Using OpenAI URL directly (dev mode or no blob storage)');
      finalImageUrl = openaiImageURL;
    }

    console.log('[Image Generation] Success! Image available at:', finalImageUrl);

    return NextResponse.json({
      success: true,
      imageUrl: finalImageUrl,
      prompt,
      fileName,
    });

  } catch (error) {
    console.error('[Image Generation] Error:', error);
    console.error('[Image Generation] Error details:', error instanceof Error ? error.message : 'Unknown error');
    return NextResponse.json(
      { 
        error: 'Failed to generate fighter image',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}

